### ISSUE TITLE
A request 🙏🏻 

### ISSUE THREAD

**Issue by mat2ja** [matijao/Server-side-Development-with-NodeJS-Express-and-MongoDB#1]
Hi man, sorry for opening non-related issue but been trying to contact you some way for a long time now (account has been inactive until now).

I know it's a long shot, but... is there any chance you'd be interested in changing your GitHub username so I could get `@matijao`?
I know it's a strange request, but I already use `matijao` on pretty much all of my networks, even got [matijao.com](https://matijao.com/links) for my personal site. GitHub is the (most important) piece I'm missing. 😅

Thank you either way.

Sretna Nova from Croatia! 🇭🇷

**Comment by matijao** [comment]
Dear Matija,

Thank you for contacting me, no problem.

I am also a sw developer but have been using another repo tools. I am planning to use github in the future so need to move repos either. By now i have here two only so not such a problem to adopt althoug it is also a bit inconvenient for me since it's my commonly used username to access various platforms. 

I can give it to you but can't be for free. How much do you think would be fair price fo this username?

BR,
Matija

**Comment by mat2ja** [comment]
Hi, thank you for responding.

In case of a username change, you don't actually need to move repos or do anything at all, it's just a single setting in personal settings. Here's more on it, from [github docs ](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/changing-your-github-username).

I've actually tried it a few times in the past, all went smoothly.

From your side, nothing at all would change, you'd only have to update your GitHub link if you linked it somewhere (i.e. your LinkedIn or resume).  
From my side, I have some mentions in issues and pull requests in various open source projects as of lately, and have linked up my projects at bunch of places, but I don't think losing these references is very important. And GitHub will still redirect to my profile until someone takes my current username.

If you have Twitter, Telegram, LinkedIn or Discord, we could discuss more on it there, as this is all public.

As for payment, to be honest I don't know how much stuff like this is worth. But I'm sure we can agree on something, if it's not too unreasonable.
Just for context, my matijao.com domain with SSL cost me like $9/yr.

Cheers

✌🏻
